## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := arm64-darwin20-gcc
ALL_TARGETS += libs
ALL_TARGETS += examples

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp8-vp9-nodocs-arm64-darwin20-v1.15.1
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=v1.15.1

VERSION_MAJOR=1
VERSION_MINOR=15
VERSION_PATCH=1

CONFIGURE_ARGS=--target=arm64-darwin20-gcc --enable-vp8 --enable-vp9 --enable-vp9-highbitdepth --enable-postproc --enable-vp9-postproc --enable-multithread --enable-runtime-cpu-detect --disable-unit-tests --disable-docs --disable-tools
CONFIGURE_ARGS?=--target=arm64-darwin20-gcc --enable-vp8 --enable-vp9 --enable-vp9-highbitdepth --enable-postproc --enable-vp9-postproc --enable-multithread --enable-runtime-cpu-detect --disable-unit-tests --disable-docs --disable-tools
