## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
SRC_PATH="/Users/hypernewbie/code/vvpx/libvpx_neon_build_final"
SRC_PATH_BARE=/Users/hypernewbie/code/vvpx/libvpx_neon_build_final
BUILD_PFX=
TOOLCHAIN=arm64-darwin20-gcc
ASM_CONVERSION=/Users/hypernewbie/code/vvpx/libvpx_neon_build_final/build/make/ads2gas.pl
GEN_VCPROJ=
MSVS_ARCH_DIR=

CC=gcc
CXX=g++
AR=ar
LD=g++
AS=as
STRIP=strip

CFLAGS  =  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -arch arm64 -march=armv8-a -DNDEBUG -O3 -fPIC -Wall -Wdisabled-optimization -Wextra-semi -Wextra-semi-stmt -Wfloat-conversion -Wformat=2 -Wparentheses-equality -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wshadow -Wstrict-prototypes -Wuninitialized -Wunreachable-code-aggressive -Wunused -Wextra -Wundef -Wframe-larger-than=52000 -std=gnu99 -Wshorten-64-to-32 -flax-vector-conversions=none
CXXFLAGS  =  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -arch arm64 -march=armv8-a -DNDEBUG -O3 -fPIC -Wall -Wdisabled-optimization -Wextra-semi -Wextra-semi-stmt -Wfloat-conversion -Wformat=2 -Wparentheses-equality -Wpointer-arith -Wtype-limits -Wcast-qual -Wvla -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wshadow -Wstrict-prototypes -Wuninitialized -Wunreachable-code-aggressive -Wunused -Wextra -flax-vector-conversions=none -Wno-psabi -Wc++14-extensions -Wc++17-extensions -Wc++20-extensions -Wnon-virtual-dtor -std=gnu++11 -std=gnu++11
ARFLAGS = -crs$(if $(quiet),,v)
LDFLAGS =  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -arch arm64
ASFLAGS =  -march=armv8-a
extralibs =  -lpthread
AS_SFX    = .S
EXE_SFX   = 
VCPROJ_SFX = 
RTCD_OPTIONS = 
LIBWEBM_CXXFLAGS =  -Wno-shadow
LIBYUV_CXXFLAGS =  -Wno-missing-declarations -Wno-missing-prototypes -Wno-pass-failed -Wno-shadow -Wno-unused-parameter
fmt_deps = sed -e 's;^\([a-zA-Z0-9_]*\)\.o;${@:.d=.o} $@;'
VPX_ARCH_ARM=yes
VPX_ARCH_AARCH64=yes
HAVE_NEON=yes
HAVE_NEON_DOTPROD=yes
HAVE_NEON_I8MM=yes
HAVE_SVE=yes
HAVE_SVE2=yes
HAVE_VPX_PORTS=yes
HAVE_PTHREAD_H=yes
HAVE_UNISTD_H=yes
CONFIG_DEPENDENCY_TRACKING=yes
CONFIG_INSTALL_BINS=yes
CONFIG_INSTALL_LIBS=yes
CONFIG_GCC=yes
CONFIG_PIC=yes
CONFIG_RUNTIME_CPU_DETECT=yes
CONFIG_POSTPROC=yes
CONFIG_VP9_POSTPROC=yes
CONFIG_MULTITHREAD=yes
CONFIG_VP8_ENCODER=yes
CONFIG_VP8_DECODER=yes
CONFIG_VP9_ENCODER=yes
CONFIG_VP9_DECODER=yes
CONFIG_VP8=yes
CONFIG_VP9=yes
CONFIG_ENCODERS=yes
CONFIG_DECODERS=yes
CONFIG_SPATIAL_RESAMPLING=yes
CONFIG_STATIC=yes
CONFIG_OS_SUPPORT=yes
CONFIG_WEBM_IO=yes
CONFIG_LIBYUV=yes
CONFIG_TEMPORAL_DENOISING=yes
CONFIG_VP9_HIGHBITDEPTH=yes
