# Auto-generated from libvpx/SMP/libvpx_files.props (Filtered for Generic C)
# Do not edit manually - re-run scripts/extract_sources.py

set(VPX_C_SOURCES_ARM
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/alloccommon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/blockd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/debugmodes.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/dequantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropymode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropymv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/extend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/findnearmv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/generic/systemdependent.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/idct_blk.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/idctllm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/loopfilter_filters.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/mbpitch.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/mfqe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/modecont.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/postproc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/quant_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconinter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconintra.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconintra4x4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/setupintrarecon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/swapyv12buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/treecoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/vp8_loopfilter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/vp8_skin_detection.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/dboolhuff.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/decodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/decodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/detokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/onyxd_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/threading.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/bitstream.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/boolhuff.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/copy_c.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/dct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/denoising.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodeintra.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodemb.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/ethreading.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/firstpass.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/lookahead.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/mcomp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/modecosts.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/onyx_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/pickinter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/picklpf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/ratectrl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/rdopt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/segmentation.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/temporal_filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/tokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/treewriter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/vp8_quantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/vp8_cx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/vp8_dx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_alloccommon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_blockd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_common_data.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_debugmodes.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropymode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropymv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_frame_buffers.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_idct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_loopfilter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_mvref_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_pred_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_quant_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_reconinter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_reconintra.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_scale.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_scan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_seg_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_thread_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_tile_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_detokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_dsubexp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_job_queue.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_alt_ref_aq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_360.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_complexity.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_cyclicrefresh.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_variance.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_bitstream.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_blockiness.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_context_tree.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_cost.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_dct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodemb.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ethread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ext_ratectrl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_extend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_firstpass.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_frame_scale.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_lookahead.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_mbgraph.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_mcomp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_multi_thread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_noise_estimate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_picklpf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_pickmode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_quantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ratectrl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_rd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_rdopt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_resize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_segmentation.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_skin_detection.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_speed_features.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_subexp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_svc_layercontext.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_temporal_filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_tokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_tpl_model.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_treewriter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_cx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_dx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_iface_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_codec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_decoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_encoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_image.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/add_noise.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/avg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitreader.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitreader_buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitwriter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitwriter_buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/deblock.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/fwd_txfm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/intrapred.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/inv_txfm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/loopfilter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/prob.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/psnr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/quantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/sad.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/skin_detection.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/sse.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/subtract.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/sum_squares.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/variance.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/vpx_convolve.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/vpx_dsp_rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_mem/vpx_mem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/gen_scalers.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/vpx_scale.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/yv12config.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/yv12extend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/vpx_scale_rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_thread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_write_yuv_frame.c
)

set(VPX_HEADERS_ARM
    ${VPX_HEADERS}
)