# ARM NEON optimised sources for macOS ARM64
set(VPX_NEON_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/bilinearpredict_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/copymem_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/dc_only_idct_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/dequant_idct_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/dequantizeb_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/idct_blk_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/iwalsh_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/loopfiltersimplehorizontaledge_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/loopfiltersimpleverticaledge_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/mbloopfilter_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/shortidct4x4llm_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/sixtappredict_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/neon/vp8_loopfilter_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/arm/neon/denoising_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/arm/neon/fastquantizeb_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/arm/neon/shortfdct_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/arm/neon/vp8_shortwalsh4x4_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/arm/neon/vp9_highbd_iht16x16_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/arm/neon/vp9_highbd_iht4x4_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/arm/neon/vp9_highbd_iht8x8_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/arm/neon/vp9_iht16x16_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/arm/neon/vp9_iht4x4_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/arm/neon/vp9_iht8x8_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_dct_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_diamond_search_sad_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_error_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_frame_scale_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_highbd_error_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_highbd_temporal_filter_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_quantize_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/arm/neon/vp9_temporal_filter_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/avg_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/avg_pred_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/deblock_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/fdct16x16_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/fdct32x32_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/fdct4x4_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/fdct8x8_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/fdct_partial_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/hadamard_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_avg_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_avg_pred_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_hadamard_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_idct16x16_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_idct32x32_1024_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_idct32x32_135_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_idct32x32_34_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_idct32x32_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_idct4x4_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_idct8x8_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_intrapred_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_loopfilter_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_quantize_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_sad4d_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_sad_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_sse_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_subpel_variance_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_variance_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_variance_neon_dotprod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_vpx_convolve8_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_vpx_convolve_avg_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/highbd_vpx_convolve_copy_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct16x16_1_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct16x16_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct32x32_135_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct32x32_1_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct32x32_34_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct32x32_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct4x4_1_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct4x4_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct8x8_1_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/idct8x8_add_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/intrapred_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/loopfilter_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/quantize_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/sad4d_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/sad4d_neon_dotprod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/sad_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/sad_neon_dotprod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/sse_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/sse_neon_dotprod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/subpel_variance_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/subtract_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/sum_squares_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/variance_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/variance_neon_dotprod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/vpx_convolve8_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/vpx_convolve8_neon_dotprod.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/vpx_convolve_avg_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/vpx_convolve_copy_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/vpx_convolve_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/arm/vpx_scaled_convolve8_neon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/aarch64_cpudetect.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/loopfilter_arm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_postproc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/arm/loopfilter_arm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_postproc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_mfqe.c
)
