# Auto-generated from libvpx/SMP/libvpx_files.props
# Do not edit manually - re-run scripts/extract_sources.py

set(VPX_C_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/alloccommon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/blockd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/debugmodes.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/dequantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropymode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropymv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/extend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/findnearmv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/generic/systemdependent.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/idct_blk.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/idctllm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/loopfilter_filters.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/mbpitch.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/mfqe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/modecont.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/postproc.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/quant_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconinter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconintra.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconintra4x4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/setupintrarecon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/swapyv12buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/treecoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/vp8_loopfilter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/vp8_skin_detection.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/bilinear_filter_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/idct_blk_mmx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/idct_blk_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/loopfilter_x86.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/vp8_asm_stubs.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/dboolhuff.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/decodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/decodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/detokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/onyxd_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/threading.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/bitstream.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/boolhuff.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/copy_c.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/dct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/denoising.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodeintra.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodemb.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/ethreading.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/firstpass.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/lookahead.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/mcomp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/modecosts.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/onyx_if.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/pickinter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/picklpf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/ratectrl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/rdopt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/segmentation.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/temporal_filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/tokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/treewriter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/vp8_quantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/denoising_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/quantize_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/vp8_enc_stubs_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/vp8_quantize_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/vp8_quantize_ssse3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/vp8_cx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/vp8_dx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_alloccommon.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_blockd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_common_data.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_debugmodes.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropy.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropymode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropymv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_frame_buffers.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_idct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_loopfilter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_mvref_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_pred_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_quant_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_reconinter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_reconintra.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_scale.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_scan.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_seg_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_thread_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_tile_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/x86/vp9_highbd_iht16x16_add_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/x86/vp9_highbd_iht4x4_add_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/x86/vp9_highbd_iht8x8_add_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/x86/vp9_idct_intrin_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_detokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_dsubexp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_job_queue.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_alt_ref_aq.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_360.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_complexity.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_cyclicrefresh.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_variance.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_bitstream.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_blockiness.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_context_tree.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_cost.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_dct.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodeframe.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodemb.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodemv.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ethread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ext_ratectrl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_extend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_firstpass.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_frame_scale.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_lookahead.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_mbgraph.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_mcomp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_multi_thread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_noise_estimate.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_picklpf.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_pickmode.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_quantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ratectrl.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_rd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_rdopt.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_resize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_segmentation.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_skin_detection.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_speed_features.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_subexp.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_svc_layercontext.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_temporal_filter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_tokenize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_tpl_model.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_treewriter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/highbd_temporal_filter_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/temporal_filter_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_dct_intrin_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_error_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_frame_scale_ssse3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_highbd_block_error_intrin_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_quantize_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_quantize_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_quantize_ssse3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_cx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_dx_iface.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_iface_common.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_codec.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_decoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_encoder.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/src/vpx_image.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/add_noise.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/avg.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitreader.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitreader_buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitwriter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitwriter_buffer.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/deblock.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/fwd_txfm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/intrapred.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/inv_txfm.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/loopfilter.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/prob.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/psnr.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/quantize.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/sad.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/skin_detection.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/sse.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/subtract.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/sum_squares.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/variance.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/vpx_convolve.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/vpx_dsp_rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/avg_intrin_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/avg_intrin_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/avg_pred_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/avg_pred_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/fwd_txfm_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/fwd_txfm_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_convolve_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct16x16_add_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct16x16_add_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct32x32_add_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct32x32_add_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct4x4_add_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct4x4_add_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct8x8_add_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_idct8x8_add_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_intrapred_intrin_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_intrapred_intrin_ssse3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_loopfilter_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_quantize_intrin_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_quantize_intrin_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_sad4d_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_sad_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_variance_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/inv_txfm_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/inv_txfm_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/inv_txfm_ssse3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/loopfilter_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/loopfilter_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/post_proc_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/quantize_avx.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/quantize_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/quantize_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/quantize_ssse3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sad4d_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sad4d_avx512.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sad_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sse_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sse_sse4.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/subtract_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sum_squares_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/variance_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/variance_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_subpixel_4t_intrin_sse2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_subpixel_8t_intrin_avx2.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_subpixel_8t_intrin_ssse3.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_mem/vpx_mem.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/gen_scalers.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/vpx_scale.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/yv12config.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/generic/yv12extend.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/vpx_scale_rtcd.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_thread.c
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_write_yuv_frame.c
)

set(VPX_X86_ASM_SOURCES
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/dequantize_mmx.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/idctllm_mmx.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/idctllm_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/iwalsh_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/loopfilter_block_sse2_x86_64.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/loopfilter_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/mfqe_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/recon_mmx.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/recon_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/subpixel_mmx.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/subpixel_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/x86/subpixel_ssse3.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/block_error_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/copy_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/copy_sse3.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/dct_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/fwalsh_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/x86/temporal_filter_apply_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/x86/vp9_mfqe_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_dct_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/x86/vp9_error_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/add_noise_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/avg_ssse3_x86_64.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/bitdepth_conversion_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/deblock_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/fwd_txfm_ssse3_x86_64.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_intrapred_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_sad4d_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_sad_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_subpel_variance_impl_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_variance_impl_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/intrapred_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/intrapred_ssse3.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/inv_wht_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sad4d_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/sad_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/ssim_opt_x86_64.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/subpel_variance_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/subtract_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_convolve_copy_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_high_subpixel_8t_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_high_subpixel_bilinear_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_subpixel_8t_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_subpixel_8t_ssse3.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_subpixel_bilinear_sse2.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/vpx_subpixel_bilinear_ssse3.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/emms_mmx.asm
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/float_control_word.asm
)

set(VPX_HEADERS
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/alloccommon.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/blockd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropymode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/entropymv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/extend.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/filter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/findnearmv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/header.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/loopfilter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/modecont.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/postproc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/quant_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconinter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconintra.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/reconintra4x4.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/setupintrarecon.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/swapyv12buffer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/treecoder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/common/vp8_skin_detection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/dboolhuff.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/decodemv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/decoderthreading.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/detokenize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/onyxd_int.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/decoder/treereader.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/bitstream.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/block.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/boolhuff.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/dct_value_cost.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/dct_value_tokens.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/defaultcoefcounts.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/denoising.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodeframe.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodeintra.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodemb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/encodemv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/ethreading.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/firstpass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/lookahead.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/mcomp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/modecosts.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/onyx_int.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/pickinter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/picklpf.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/quantize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/ratectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/rdopt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/segmentation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/temporal_filter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/tokenize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp8/encoder/treewriter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_alloccommon.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_blockd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_common_data.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropymode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_entropymv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_enums.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_filter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_frame_buffers.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_idct.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_loopfilter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_mfqe.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_mv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_mvref_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_ppflags.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_pred_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_quant_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_reconinter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_reconintra.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_scale.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_scan.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_seg_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_thread_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/common/vp9_tile_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decodeframe.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decodemv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_decoder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_detokenize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_dsubexp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/decoder/vp9_job_queue.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_alt_ref_aq.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_360.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_complexity.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_cyclicrefresh.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_aq_variance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_bitstream.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_block.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_blockiness.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_context_tree.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_cost.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_denoiser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodeframe.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodemb.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encodemv.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_encoder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ethread.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ext_ratectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_extend.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_firstpass.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_firstpass_stats.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_job_queue.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_lookahead.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_mbgraph.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_mcomp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_multi_thread.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_noise_estimate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_partition_models.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_picklpf.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_pickmode.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_quantize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_ratectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_rd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_rdopt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_resize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_segmentation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_skin_detection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_speed_features.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_subexp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_svc_layercontext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_temporal_filter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_tokenize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_tpl_model.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/encoder/vp9_treewriter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_dx_iface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vp9/vp9_iface_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/internal/vpx_codec_internal.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vp8.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vp8cx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vp8dx.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_codec.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_decoder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_encoder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_ext_ratectrl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_frame_buffer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_image.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_integer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx/vpx_tpl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitreader.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitreader_buffer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitwriter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/bitwriter_buffer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/fwd_txfm.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/inv_txfm.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/postproc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/prob.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/psnr.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/quantize.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/skin_detection.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/txfm_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/variance.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/vpx_convolve.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/vpx_dsp_common.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/vpx_filter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/bitdepth_conversion_avx2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/bitdepth_conversion_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/convolve.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/convolve_avx2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/convolve_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/convolve_ssse3.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/fwd_dct32x32_impl_avx2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/fwd_dct32x32_impl_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/fwd_txfm_impl_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/fwd_txfm_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_inv_txfm_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/highbd_inv_txfm_sse4.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/inv_txfm_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/inv_txfm_ssse3.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/mem_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/quantize_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/quantize_ssse3.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/transpose_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_dsp/x86/txfm_common_sse2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_mem/include/vpx_mem_intrnl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_mem/vpx_mem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/bitops.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/compiler_attributes.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/emmintrin_compat.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/mem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/mem_ops.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/mem_ops_aligned.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/static_assert.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/system_state.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/vpx_once.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/vpx_timer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_ports/x86.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/vpx_scale.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_scale/yv12config.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/endian_inl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_atomics.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_thread.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_timestamp.h
    ${CMAKE_CURRENT_SOURCE_DIR}/libvpx/vpx_util/vpx_write_yuv_frame.h
)